name: 'dartalog'
version: 0.0.1
description: A web app built using polymer.dart.
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.17.0 <2.0.0'

dependencies:
  browser: ^0.10.0
  polymer_elements: ^1.0.0-rc.8
  polymer: ^1.0.0-rc.16
  web_components: ^0.12.0
  route_hierarchical: ^0.7.0
  html: any

  args: any
  rpc: ^0.5.6
  shelf: ^0.6.5
  shelf_static:
    git: https://github.com/dartalog/shelf_static.git
  #shelf_static: ^0.2.3
  shelf_rpc: ^0.0.3
  shelf_route: any
  shelf_auth: ^0.7.1
  shelf_exception_handler: any
  option: any
  discoveryapis_generator: any
  crypto: ^0.9.0
  crypt: ^1.0.2
  _discoveryapis_commons: ^0.1.0
  image: ^1.1.26

  mongo_dart: ^0.2.5
  connection_pool: ^0.1.0

  http: ^0.11.3
  http_server: ^0.9.5
  uuid: ^0.5.1
  options_file: ^0.11.0
  logging_handlers: ^0.8.0
  # 0.27.3 has a bug with paths on Windows
  analyzer: 0.27.2

  test: any
transformers:
- polymer:
    entry_points:
      - web/index.html
      - web/setup/index.html
- $dart2js:
    minify: true
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives
