name: 'dartalog'
version: 0.0.1
description: A web app built using polymer.dart.
#author: <your name> <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  args: 'any'
  browser: 'any'
  paper_elements: 'any'
  core_elements: 'any'
  polymer: 'any'
  rpc: 'any'
  logging: 'any'
  logging_handlers: 'any'
  shelf: 'any'
  shelf_static: 'any'
  shelf_rpc: 'any'
  shelf_auth: 'any'
  shelf_oauth: 'any'
  mongo_dart: 'any'
  connection_pool: 'any'
  options_file: 'any'
  uuid: 'any'
  http: 'any'
  crypto: 'any'
  route_hierarchical: 'any'
  _discoveryapis_commons: 'any'
  http_server: 'any'
  discoveryapis_generator: 'any'
transformers:
- polymer:
    entry_points: web/index.html
