name: 'dartalog'
version: 0.1.0
description: Library management application
author: Matthew Barbour <sanmadjack@gmail.com>
homepage: https://github.com/dartalog

environment:
  sdk: '>=1.17.0 <2.0.0'

dependencies:
  # analyzer 0.27.3 has a bug with paths on Windows
  analyzer: 0.27.2
  args: ^0.13.4
  browser: ^0.10.0
  connection_pool: ^0.1.0
  crypt: ^1.0.2
  crypto: ^0.9.2
  _discoveryapis_commons: ^0.1.3
  discoveryapis_generator: ^0.7.2
  html: ^0.12.2
  http: ^0.11.3
  http_server: ^0.9.5
  image: ^1.1.26
  logging_handlers: ^0.8.0
  mime: ^0.9.3
  mongo_dart: ^0.2.7
  option: ^1.2.0
  options_file: ^0.11.0
  polymer_elements: ^1.0.0-rc.8
  polymer: ^1.0.0-rc.17
  quagga_dart: ^0.0.2
  route_hierarchical: ^0.7.0
  rpc: ^0.5.6
  shelf: ^0.6.5
  shelf_auth: ^0.7.2
  shelf_exception_handler: ^0.1.0
  shelf_route: ^0.13.1
  shelf_rpc: ^0.0.3
  shelf_static:
    git: https://github.com/dartalog/shelf_static.git
  #shelf_static: ^0.2.3
  #test: any
  web_components: ^0.12.3
executables:
  dartalog-server: server.dart
transformers:
- polymer:
    entry_points:
      - web/index.html
      - web/setup/index.html
- $dart2js:
    minify: true
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives
